// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Infrastructure.Data;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20250916091956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("Priority");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Setup",
                            CreatedAt = new DateTime(2025, 9, 16, 9, 19, 53, 893, DateTimeKind.Utc).AddTicks(5251),
                            Description = "Install and configure PostgreSQL for the Todo application",
                            IsCompleted = false,
                            Priority = 3,
                            Title = "Setup PostgreSQL Database"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Development",
                            CreatedAt = new DateTime(2025, 9, 16, 9, 19, 53, 893, DateTimeKind.Utc).AddTicks(5255),
                            Description = "Implement CRUD operations for Todo items",
                            IsCompleted = false,
                            Priority = 3,
                            Title = "Create API Endpoints"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Documentation",
                            CreatedAt = new DateTime(2025, 9, 16, 9, 19, 53, 893, DateTimeKind.Utc).AddTicks(5257),
                            Description = "Configure Swagger for API documentation",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Add Swagger Documentation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
